In [6]:
#Loading Data

import pandas as pd
ecommerce_df = pd.read_csv('global_ecommerce_sales.csv')
ecommerce_df.head()

,Order_ID,Order_Date,Customer_Name,Customer_Segment,Country,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Payment_Method
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery
2,ORD-10325,2023-01-03,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card
3,ORD-10467,2023-01-03,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal
4,ORD-11454,2023-01-05,Felix Thomas,Consumer,Italy,Europe,Furniture,Standing Desk Converter,4,330.67,20,1058.14,11.09,253.44,Credit Card

In [ ]:
#Dataset Structure

ecommerce_df.head()
ecommerce_df.info()
ecommerce_df.shape

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2000 non-null   str
 1   Order_Date        2000 non-null   str
 2   Customer_Name     2000 non-null   str
 3   Customer_Segment  2000 non-null   str
 4   Country           2000 non-null   str
 5   Region            2000 non-null   str
 6   Product_Category  2000 non-null   str
 7   Product_Name      2000 non-null   str
 8   Quantity          2000 non-null   int64
 9   Unit_Price        2000 non-null   float64
 10  Discount_Percent  2000 non-null   int64
 11  Total_Sales       2000 non-null   float64
 12  Shipping_Cost     2000 non-null   float64
 13  Profit            2000 non-null   float64
 14  Payment_Method    2000 non-null   str
dtypes: float64(4), int64(2), str(9)
memory usage: 234.5 KB

(2000, 15)

In [9]:
# Explore Individual Columns

ecommerce_df['Product_Category'].value_counts()
ecommerce_df['Total_Sales'].describe()

count    2000.000000
mean      242.279670
std       382.583802
min         2.420000
25%        41.227500
50%       113.125000
75%       266.552500
max      3813.980000
Name: Total_Sales, dtype: float64

In [13]:
#cleaning and wrangling

ecommerce_df.loc[
    ecommerce_df['Total_Sales'] > 500,
    ['Country', 'Total_Sales', 'Product_Category']
]

           Country  Total_Sales        Product_Category
4            Italy      1058.14               Furniture
8            China       634.81               Furniture
16         Nigeria       914.43               Furniture
17       Australia       848.92               Furniture
18          Mexico       579.48               Furniture
...            ...          ...                     ...
1966  South Africa       617.46               Furniture
1970   South Korea       827.42               Furniture
1992         Italy       969.81               Furniture
1995        France       523.65               Furniture
1996        France       619.37  Clothing & Accessories

[257 rows x 3 columns]

In [33]:
df = (ecommerce_df['Total_Sales'] > 100) & (ecommerce_df["Country"] == "Italy")

ecommerce_df.loc[df].iloc[:, 0:3]

       Order_ID  Order_Date       Customer_Name
3     ORD-10467  2023-01-03        Clara Taylor
4     ORD-11454  2023-01-05        Felix Thomas
34    ORD-11035  2023-01-25         Linda Russo
48    ORD-10950  2023-02-02      William Sharma
68    ORD-11659  2023-02-10       Emma Oliveira
94    ORD-11598  2023-02-26      Ingrid Schmidt
117   ORD-11668  2023-03-10     Robert Robinson
267   ORD-11535  2023-06-11    Isabella Jackson
276   ORD-10569  2023-06-17         Chen Miller
277   ORD-11665  2023-06-18       Priya Jackson
311   ORD-10112  2023-07-07      Ahmed Thompson
322   ORD-10545  2023-07-13  Elizabeth Williams
402   ORD-11529  2023-08-22    Patricia Jackson
405   ORD-10738  2023-08-23            Liam Ali
409   ORD-11515  2023-08-25     Ethan Rodriguez
447   ORD-11544  2023-09-10         Noah Moreau
486   ORD-10421  2023-10-03      Noah Johansson
505   ORD-11091  2023-10-09      Layla Oliveira
527   ORD-11245  2023-10-20        Nadia Tanaka
541   ORD-10530  2023-10-26              Ali Li
616   ORD-10220  2023-12-08     Elizabeth Weber
671   ORD-11510  2024-01-01        Olga Pereira
744   ORD-10510  2024-02-18     Olivia Anderson
755   ORD-10947  2024-03-03         Kenji Davis
867   ORD-10456  2024-05-04        Wei Martinez
868   ORD-10732  2024-05-04         Lucas Russo
883   ORD-11817  2024-05-11          Ava Harris
894   ORD-10169  2024-05-18      Hanna Robinson
949   ORD-11882  2024-06-16            Liam Kim
1038  ORD-10910  2024-08-09         Felix White
1051  ORD-10448  2024-08-16        Lucas Moreau
1075  ORD-10055  2024-08-31           Hans Park
1115  ORD-10998  2024-09-18        Diego Miller
1155  ORD-10663  2024-10-09         Hans Miller
1193  ORD-11037  2024-10-26     Fatima Williams
1202  ORD-11455  2024-10-29         Omar Thomas
1229  ORD-11629  2024-11-09        Thomas Costa
1253  ORD-11758  2024-11-22         Priya Smith
1300  ORD-11476  2024-12-16           Ava Rossi
1361  ORD-11115  2025-01-30        Kenji Martin
1365  ORD-10644  2025-02-03           Mia Weber
1369  ORD-11509  2025-02-05         Priya Singh
1385  ORD-11839  2025-02-18           Li Suzuki
1468  ORD-11591  2025-04-09        Priya Romano
1476  ORD-11438  2025-04-11          Olga Russo
1568  ORD-10851  2025-05-20         Emma Martin
1608  ORD-10428  2025-06-10         Felix Patel
1672  ORD-10192  2025-07-15         Wei Laurent
1744  ORD-10739  2025-08-27          Amir Brown
1755  ORD-10965  2025-09-02      Clara Robinson
1786  ORD-10628  2025-09-19         Joseph Wang
1792  ORD-10940  2025-09-23    Robert Rodriguez
1876  ORD-10566  2025-10-31       Giulia Harris
1909  ORD-11102  2025-11-17        William Sato
1976  ORD-10268  2025-12-21   Elizabeth Fischer
1992  ORD-10188  2025-12-30    Elizabeth Müller

In [37]:
ecommerce_df.sort_values(by='Customer_Name', ascending=True)

,Order_ID,Order_Date,Customer_Name,Customer_Segment,Country,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Payment_Method
1291,ORD-11384,2024-12-13,Ahmed Ali,Consumer,Mexico,North America,Clothing & Accessories,Cotton Formal Shirt,12,44.66,5,509.12,14.12,227.04,Credit Card
1064,ORD-10629,2024-08-25,Ahmed Anderson,Home Office,China,Asia Pacific,Technology,Smart LED Desk Lamp,4,33.42,0,133.68,13.19,46.97,PayPal
47,ORD-10787,2023-02-01,Ahmed Clark,Consumer,Canada,North America,Technology,Tablet Stand Holder,3,19.94,0,59.82,8.61,18.31,Bank Transfer
806,ORD-10064,2024-04-05,Ahmed Clark,Corporate,Japan,Asia Pacific,Clothing & Accessories,Cotton Formal Shirt,1,43.07,20,34.46,10.50,2.43,Bank Transfer
1958,ORD-10888,2025-12-09,Ahmed Dubois,Consumer,Spain,Europe,Technology,Tablet Stand Holder,1,45.07,5,42.82,9.42,8.61,Cash on Delivery
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,ORD-11908,2024-12-15,Zara Weber,Consumer,Japan,Asia Pacific,Office Supplies,Highlighters Neon Pack 6,4,12.49,5,47.46,14.76,10.22,Bank Transfer
886,ORD-11104,2024-05-14,Zara White,Consumer,UAE,Middle East & Africa,Office Supplies,Ballpoint Pen Pack 12,5,10.88,5,51.68,16.95,10.25,Credit Card
91,ORD-11205,2023-02-24,Zara White,Consumer,France,Europe,Office Supplies,Binder Clips Assorted 48pc,6,7.14,0,42.84,12.59,10.97,PayPal
1238,ORD-10150,2024-11-17,Zara Williams,Consumer,Japan,Asia Pacific,Technology,Noise Cancelling Earbuds,7,123.89,0,867.23,19.56,370.69,Credit Card
1800,ORD-10552,2025-09-26,Zara Williams,Consumer,Spain,Europe,Technology,Wireless Bluetooth Headphones,2,153.30,5,291.27,8.25,114.39,Cash on Delivery

In [39]:
ecommerce_df.rename(columns={
    "Total_Sales": "Sales"
}, inplace=True)
ecommerce_df.head()

,Order_ID,Order_Date,Customer_Name,Customer_Segment,Country,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Sales,Shipping_Cost,Profit,Payment_Method
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery
2,ORD-10325,2023-01-03,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card
3,ORD-10467,2023-01-03,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal
4,ORD-11454,2023-01-05,Felix Thomas,Consumer,Italy,Europe,Furniture,Standing Desk Converter,4,330.67,20,1058.14,11.09,253.44,Credit Card

In [41]:
ecommerce_df.drop(columns=['Region'], inplace=True)

In [47]:


ecommerce_df["Order_Date"] = pd.to_datetime(ecommerce_df["Order_Date"])
ecommerce_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2000 non-null   str
 1   Order_Date        2000 non-null   datetime64[us]
 2   Customer_Name     2000 non-null   str
 3   Customer_Segment  2000 non-null   str
 4   Country           2000 non-null   str
 5   Product_Category  2000 non-null   str
 6   Product_Name      2000 non-null   str
 7   Quantity          2000 non-null   int64
 8   Unit_Price        2000 non-null   float64
 9   Discount_Percent  2000 non-null   int64
 10  Sales             2000 non-null   float64
 11  Shipping_Cost     2000 non-null   float64
 12  Profit            2000 non-null   float64
 13  Payment_Method    2000 non-null   str
dtypes: datetime64[us](1), float64(4), int64(2), str(7)
memory usage: 218.9 KB

In [51]:
ecommerce_df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_Name       0
Customer_Segment    0
Country             0
Product_Category    0
Product_Name        0
Quantity            0
Unit_Price          0
Discount_Percent    0
Sales               0
Shipping_Cost       0
Profit              0
Payment_Method      0
dtype: int64

In [55]:
ecommerce_df.duplicated()
ecommerce_df[ecommerce_df.duplicated()]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_Name, Customer_Segment, Country, Product_Category, Product_Name, Quantity, Unit_Price, Discount_Percent, Sales, Shipping_Cost, Profit, Payment_Method]
Index: []

In [64]:
ecommerce_df.head()
ecommerce_df["Country"].unique()
ecommerce_df["Payment_Method"].unique()
ecommerce_df["Product_Category"].value_counts()
ecommerce_df["Customer_Segment"].unique()
ecommerce_df["Order_Date"].dtype

dtype('<M8[us]')

In [ ]:
ecommerce_df[ecommerce_df["Sales"] < 0]
ecommerce_df[ecommerce_df["Profit"] < 0]

KeyError: "['check_Profit'] not in index"